services:
  ch08:
    image: dhzacur/ha_ch09_brk
    container_name: ch09-brk
    hostname: ch09-brk
    ports:
      -  41048:41048
    volumes:
      -  ${LOG_PATH}:/etc/ch09-brk/logs
      -  ${CONFIG_PATH}/.env:/app/.env
      -  ${CERT_PATH}:/app/certificados      
    networks:
      habitatzone:
        ipv4_address: 172.30.0.248
    restart: unless-stopped
networks:
  habitatzone:
    external: true