services:
  ch09:
    image: dhzacur/ha_ch09_brk
    container_name: ch09-brk
    hostname: ch09-brk
    ports:
      -  ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
      -  ${LOG_PATH}:/etc/nages2/logdir
      -  ${CONFIG_PATH}/.env:/app/.env
      -  ${CERT_PATH}:/app/certificados      
      -  ${SSH_PUBLIC_KEY_HOST_PATH}:/app/ssh-public
    environment:
      SSH_PUBLIC_KEY_EXPORT_PATH: /app/ssh-public
    networks:
      habitatzone:
        ipv4_address: ${CONTAINER_IP}
    restart: unless-stopped
networks:
  habitatzone:
    external: true
